import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {useRouter} from "next/router";
import {checkLocale} from "./local";

export default function Home() {
  const {locale} = useRouter();
  const t = checkLocale(locale);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          {t.SUBTITLE}
        </h1>

        <p className={styles.description}>
          {t.LOCALE}
        </p>
      </main>
    </div>
  )
}
